### ISSUE TITLE
Directional Shiny sound

### ISSUE THREAD

**Issue by MK-404** [timinc-cobble/cobblemon-spawnnotification#24]
It would be cool to have the shiny sound played where the shiny pokemon is spawn, so it'll be directional in game

**Comment by tmetcalfe89** [comment]
It is played at the position of the spawning Pokemon.

https://github.com/timinc-cobble/cobblemon-spawnnotification-1.4-fabric/blob/72ff2dbff3a48983635fb147b84524f23883ee80/src/main/kotlin/us/timinc/mc/cobblemon/spawnnotification/SpawnNotification.kt#L122

You might be interested in #10 instead.
